notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

os:
  - linux
  #- osx

sudo: required

addons:
  apt:
    packages:
    - curl
    - shellcheck

install:
  curl -L https://raw.githubusercontent.com/jmlntw/dotfiles/master/bin/dotfiles | bash

script:
  dotfiles test

branches:
  only:
    - master
