notifications:
  email:
    on_success: never
    on_failure: change

os:
  - linux
  - osx

sudo: required

env:
  global:
    - DOTFILES_PATH=~/.dotfiles

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_install:
  - [[ $(type -P 'brew') ]] && brew update && brew install shellcheck

install:
  - curl -L https://raw.githubusercontent.com/jmlntw/dotfiles/master/bin/dotfiles | bash

before_script:
  - cd "${DOTFILES_PATH}"

script:
  - bin/dotfiles test

branches:
  only:
    - master
