notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

os:
  - linux
  #- osx

sudo: required

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

env:
  global:
    - DOTFILES_PATH=~/.dotfiles

install:
  - curl -L https://raw.githubusercontent.com/jmlntw/dotfiles/master/bin/dotfiles | bash

before_script:
  - cd "${DOTFILES_PATH}"

script:
  - bin/dotfiles test

branches:
  only:
    - master
